name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with: {python-version: '3.12'}
      - uses: astral-sh/setup-uv@v7
      - run: make build
      - uses: actions/upload-artifact@v4
        with:
          path: build/pget_iplayer
          name: pget_iplayer
